### ISSUE TITLE
get_gdsync_owner returns void

### ISSUE THREAD

**Issue by vassembly** [GD-Sync/GD-Sync#1]
MultiplayerClient.gd - Line 356
![image](https://github.com/GD-Sync/GD-Sync/assets/53514993/342aa38b-edab-4ea6-b236-7f87db4eb641)
![image](https://github.com/GD-Sync/GD-Sync/assets/53514993/10aaf938-d397-4845-a490-12a4dbf591c5)

Changing void to int doesn't fix the issue

**Comment by ThomasUijlen** [comment]
Thank you for opening up an issue. The function in question has been fixed, as well as a few other issues related to the GD-Sync ownership system.

We're planning to roll out the patch in the next few days which includes other bug fixes as well. I will post another comment here to notify you whenever the patch has been released.

**Comment by ThomasUijlen** [comment]
Patch 0.2 has been pushed to this repo! It will take a few days for the version to be on the Godot Asset Library, as it has to be re-approved with each new version. For now, you can download it directly from here.

If you encounter any issues please let us know!
