### ISSUE TITLE
GDSync.call_func()'s "reliable" seemingly doesn't always succeed

### ISSUE THREAD

**Issue by KccbzZ** [GD-Sync/GD-Sync#10]
### GDSync Version:

Latest as of 26th July 2024 (Including username fix)

### The Problem:

When I use `GDSync.call_func()`, with `reliable` set to `true`, this remote function call is not guaranteed to succeed.

### Elaboration:

I was creating my own chat system. I made my code more readable and attached the relevant bits below, along with two images where I did some testing, just as evidence of this. It is similar to the GDSync template.

My 'chat' code, handling sending and receiving messages:
```gdscript
# This is part of my 'chat.gd' script

func _ready() -> void:
     GDSync.expose_func(receive_msg)


# Called when user presses 'Enter' or presses the 'Send' button
func send_msg(msg : String) -> void:
     GDSync.call_func(receive_msg, [msg], true) # Send msg to all other clients <--- Problem is here to my belief
     receive_msg(msg) # Send msg to myself


# Instantiates a 'RichTextLabel' with the given message (In my actual code I attach
# the sender id as a parameter to get the username too, just simplified it for the
# sake of readability)
func receive_msg(msg : String) -> void:
     var message_object = RichTextLabel.new()
     message_object.text = msg
     
     # message_parent is just a VBoxContainer
     message_parent.add_child(message_object)
```

In these screenshots below, this code is put to the test using 2 test accounts "KoobzZ" and "Bober", and I annotated the images to provide some extra detail:

![bug_report_acc_koobzz](https://github.com/user-attachments/assets/34343fef-4ac7-44b5-b04a-d192438a16f6)
![bug_report_acc_bober](https://github.com/user-attachments/assets/0cb082b4-a08c-49fe-9a3c-d618e629bdb6)

From this, I believe there's a bug which makes the `reliable` bit not work.

**Comment by ThomasUijlen** [comment]
Thank you for providing a clear description and screenshots of the issue. We will investigate it.

**Comment by ThomasUijlen** [comment]
There was indeed a server-side issue with reliable packets. It was not detecting if a received packet was reliable or unreliable correctly.

We have pushed a patch to the servers which should resolve it. Reliable packets should now handled properly without packet loss.

**Comment by KccbzZ** [comment]
Oh that's a relief because I just realized that I should've tested this in a new project before posting these issues, I was doing that just now and the issue didn't occur, I thought I did something wrong in my other project haha.

I'll keep testing during the chat creation process when I get back to that, but it seems to be fixed. Thank you! :))

**Comment by ThomasUijlen** [comment]
Closing this issue. If the issue persists just let me know.
