### ISSUE TITLE
NodeInstantiator's "instantiate_node()" function is seemingly not reliable

### ISSUE THREAD

**Issue by KccbzZ** [GD-Sync/GD-Sync#11]
### GDSync Version:

Latest as of 26th July 2024 (Including username fix)

### The Problem:

When I use **NodeInstantiator**'s `instantiate_node()` in a function, called when the signal `GDSync.client_joined` is emitted, it sometimes doesn't work fully (by fully I mean some clients drop the nodes spawned for themselves), in which case rejoining the lobby fixes it.

(I've only tested this with 2 clients)

Potentially related to #10.

### Elaboration:

I am using **NodeInstantiator** to spawn nodes that represent a player's "game options", see image below:

![image](https://github.com/user-attachments/assets/f448663c-5236-4dda-bce6-4a6487514f82)

Here's the relevant extract of my code to instantiate these across all clients:

```gdscript

func _ready() -> void:
     GDSync.client_joined.connect(_on_client_joined)

func _on_client_joined(client_id : int) -> void:
     if not GDSync.is_host(): return
     $NodeInstantiator.instantiate_node() # Perhaps is the joining client SOMETIMES not ready in time and therefore drops this? No clue.
```

Putting this code to the test, sometimes achieves this, and as mentioned above, rejoining the lobby fixes it:

![bug_report_node_instantiator](https://github.com/user-attachments/assets/4685607d-f717-4872-95b2-7454b4d2735f)

I am not entirely sure if I am misusing the **NodeInstantiator** by using it when `GDSync.client_joined` is called, or if this is a bug.

**Comment by ThomasUijlen** [comment]
Thank you for providing a clear description and screenshots of the issue. We will investigate it.

**Comment by ThomasUijlen** [comment]
Closing this as the NodeInstantiator uses GDSync.call_func() internally.
