### ISSUE TITLE
[Proposal] Add a way to instantiate different scenes without the need of several NodeInstantiators, to avoid duplicate code.

### ISSUE THREAD

**Issue by KccbzZ** [GD-Sync/GD-Sync#12]
### The Problem:

There's currently no way to instantiate different scenes with the same NodeInstantiator, (or with just the call of a function on perhaps the GDSync autoload, that also sounds nice).

For my case, this is needed for performance reasons. Not that it would be a massive headache probably, but it would likely do some good by avoiding duplicate code:

I am making an RTS prototype. I would currently have to use a NodeInstantiator in each instance of a building to spawn units, e.g. two barracks's will have a NodeInstantiator each to spawn the same unit.

### Proposed Solution:

Have a way to instantiate any scene using code, with the same functionality as NodeInstantiator. I thought of 2 ways to achieve this:

1. Modify NodeInstantiator, so it would work like so: `node_instantiator.instantiate_node(scene_path: String, target: Node)`
2. Have a function in GDSync: `GDSync.instantiate_node(scene_path: String, target: Node, replicate_on_join := true, sync_starting_changes := true)`. This would probably reduce duplicate code more.

I came up with another solution that I implemented myself, where I made an autoload called GlobalInstantiator, copied the code of NodeInstantiator into it and modified it and NodeTracker too, to accept `GlobalInstantiator.instantiate_node(scene_path: String, parent := get_tree().current_scene)` while not breaking NodeInstantiator itself. I have no clue if replication works but I probably don't need it lol.

As final thoughts, this is just an idea and perhaps it's not needed massively, but I would like to know your thoughts. I am happy to share the modified NodeTracker code and my GlobalInstantiator code if needed.

**Comment by ThomasUijlen** [comment]
Great suggestion! A global way to instantiate scenes sounds indeed very handy. It has been added to our roadmap.

**Comment by ThomasUijlen** [comment]
This feature has now been implemented, you can download it here from the repo. You can now use `GDSync.multiplayer_instantiate(scene : PackedScene, parent : Node, sync_starting_changes : bool = true, excluded_properties : PackedStringArray = [], replicate_on_join : bool = true)` to instantiate Nodes without using a NodeInstantiator.

Please let me know if you encounter any issues with it.

**Comment by ThomasUijlen** [comment]
> If enabled, any changes made to the root Node of the instantiated scene within the same frame will automatically be synchronized.

This is the description of the `sync_starting_changes` parameter. It synchronizes any changes made to the root Node of the instantiated scene. Lets pick a bullet as an example. We can set the position, speed and direction after instantiating it. These changes will automatically be applied on all other clients when the bullet is instantiated there.

When a Node is instantiated remotely it goes as followed:
`_ready() is called -> starting changes are applied -> _multiplayer_ready() is called`

As for `scene : PackedScene` or just `scene_path : String`, it does not have a performance difference. Every user still loads the scene themselves. When sending the remote instantiate request it only sends the `resource_path` of the `PackedScene`.

Closing this issue as the new function seems to work as expected.
