### ISSUE TITLE
[Proposal] Add Broadcast Mode "When Last Valid Owner"

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#15]
### This mode would simplify cases where transferring rigidbody ownership between clients would keep its current momentum persistent.

**This is probably a niche use case**, but I figured why not have a discussion about it.
There are likely sufficient workarounds with a some coding effort available.

In terms of networked rigidbodies, node ownership is a great feature to keep track of which player is currently interacting with an object (assuming that only one player can interact with a rigidbody at a time) and make the interaction as smooth and responsive as possible for the currently interacting player.

However, there is no way to use this architecture currently to easily keep the momentum of a rigidbody while also resigning owernship of a rigidbody on a client that is not the host. Resigning ownership would leave the rigidbody either without an owner, stopping positional updates entirely, or revert to host ownership if "When No Owner and Host or Owner" is set, which would stop its momentum due to the transfer.

An example case where this is undesirable would be a non-host client picking up a rigidbody, throwing or sliding it, resigning ownership in the process for the rigidbody to be interacted with by other clients (or even catched mid-air or fun stuff like that), and the rigidbody losing its momentum or even any source of positional updates.

"When Last Valid Owner" would allow the most recent _existing_ player owner to still broadcast updates for the rigidbody while still providing the option to resign the ownership for it.

**Comment by ThomasUijlen** [comment]
This broadcast mode has now been implemented. If no owner was ever assigned it broadcasts from the host. Once ownership is assigned, it will keep broadcasting for that client even when ownership is cleared. It will only switch if it is reassigned to another client or if the previous owner leaves.

Beware that it may slightly break compatibility. If you used any of the broadcast modes `WHEN_HOST_AND_NO_OWNER_OR_OWNER`, `ALWAYS` or `NEVER`, those might have shifted values.

Please let me know if you encounter any issues with this new broadcasting mode.

**Comment by ThomasUijlen** [comment]
Renamed the new broadcast mode to `WHEN_HOST_OR_LAST_VALID_OWNER`.
