### ISSUE TITLE
[Bug?] Scale property is reset on clients when syncing rotation related properties

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#16]
### Using GDSync 0.5 C# enabled

I am encountering weird scenarios where an objects scale is reset to default 1,1,1 on clients when the object has a rotation-related property synchronized with a  property synchronizer.

This objects scale is 0.5, 0.5, 0.5 in its properties:
![image](https://github.com/user-attachments/assets/e51e7476-f3f1-4996-9ecd-fe2c4b1c4537)

I need the rotation of this crank/wheel objects to be synced to clients, the synchronizer is setup like this:
![image](https://github.com/user-attachments/assets/101c6b96-7697-4622-aa09-03f9b45ac538)

This is the result on host (correct scale, smaller one) and client (wrong scale, scale is reset to 1,1,1):
![image](https://github.com/user-attachments/assets/c8dab34c-6d77-4b6b-be32-fc3ba6589355)
The scale is never touched or modified in code, I double checked this by completely removing any scripts inside of this scene except the property synchronizer.

Syncing other properties, like position or global_position, doesn't reset the scale:
![image](https://github.com/user-attachments/assets/d4f8f63a-3d80-427e-bdb2-58315eeb3be4)

As a little side note, clicking into "Property Name" field puts the curser at the back of the currently typed in property name, when starting typing tho, its jumps to the front, adding the typed letters to the front of the word and not at the back. I don't know if this is a local problem to my Godot/PC, but if not, this is very inconsistent with how normal inspector fields behave:
![demo](https://github.com/user-attachments/assets/80878bcb-bf66-4d25-8d6b-e3f7c7c40a3c)

**Comment by ThomasUijlen** [comment]
Hi there! Thank you for notifying us of this issue.

Just to confirm, does the scale stay at 0.5 if you disable interpolation?

**Comment by ThomasUijlen** [comment]
A fix for this issue has been pushed. Scale should now not reset to `(1,1,1)`.

**Comment by ThomasUijlen** [comment]
As for the inspector issue you mentioned, that problem seems to be with Godot. If the inspector is refreshed using `notify_property_list_changed()`, Godot puts the text cursor back at the beginning of the text input.

Refreshing the inspector is no longer needed with some of the new changes in the PropertySynchronizer, so this should not be an issue anymore.
