### ISSUE TITLE
[QoL] Fix or Remove false error outputs

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#18]
Fairly regulary I get error messages printed into output on starting up my GD Sync project (0.6 C# enabled,  4.4 dev):

![image](https://github.com/user-attachments/assets/9f7dd6c1-a763-4597-9e8a-e43196a93c66)

Everything seems to work just fine, but its pretty irritating nonetheless.

**EDIT: These error also pop up every time when opening up the project settings**

I don't know if this may be related but upon starting C# enabled projects, the editor also recognizes changes and marks the project as not saved, which is minor but still a bit annoying.

Overall, just some QoL / peace of mind suggestions, I appreciate your service!

**Comment by ThomasUijlen** [comment]
This should now be fixed in version 0.7.
