### ISSUE TITLE
what am I doing wrong?

### ISSUE THREAD

**Issue by ianmckenna87** [GD-Sync/GD-Sync#19]
ripped the logic and menus + scripts from the demo project and running it in my own game with my own player scenes I get one player moving with input and the other dragged along with a property sync node. but the player which is independently moving is different on each client. I feel Iv'e followed the docs the best I can to this point.

**Comment by ianmckenna87** [comment]
attached a basic example (with keys removed) as a project in case you were able to take a look
[Uploading spaceonline - Copy.zip…]()

**Comment by ThomasUijlen** [comment]
Hi there,

As this issue is not directly related to the plugin but a personal project, please send us an email at support@gd-sync.com or create a ticket on the support page on the [website](https://www.gd-sync.com/app/support). We will be able to provide further support through these methods.
