### ISSUE TITLE
Expose C# properties to PropertySynchronizers

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#21]
Hello there,

to my knowledge, custom variables of C# scripts are not accessible to PropertySynchronizers, at least they don't seem to recognize them when added to a synchronizer. So far I worked around this by having proxy GD script nodes holding the variable and setting/getting them in the C# scripts, but as the scope increases this gets very cumbersome.

Alternatively, a C#-specific version of property synchronizers would also be a solution, or at least a temporary one.

**Comment by ThomasUijlen** [comment]
Hi there,

Thank you for notifying us of this issue. Godot doesn't seem to support grabbing/reading variables directly from raw C# scripts as it does with GDScript. I've pushed a possible fix for it. It should now manually parse the scripts in search of variables.

You can grab the latest version directly here from GitHub. Please let us know if this fixes your issue!
