### ISSUE TITLE
Invalid call to function '_queue_remote (via call)' in base 'AnimationPlayer (SynchronizedAnimationPlayer.gd)'. Expected 1 arguments.

### ISSUE THREAD

**Issue by ianmckenna87** [GD-Sync/GD-Sync#22]
whenever a second player joins, I receive this error, causing client to crash. I'm on Godot 4.4 dev 3

![image](https://github.com/user-attachments/assets/26828392-498e-4e26-b7f0-ec8efb25b420)

**Comment by ianmckenna87** [comment]
update: fixed this by giving the function in the synchronized animation player a default parameter argument
![image](https://github.com/user-attachments/assets/d24b5dab-e283-42d5-a43c-77c2f79190ad)

**Comment by ThomasUijlen** [comment]
Hi there, the root cause was another bit of code in the SynchronizedAnimationPlayer. The changes have been pushed and the issue should now be resolved.
