### ISSUE TITLE
Implement Function to allow for Automatic Bans

### ISSUE THREAD

**Issue by Shando** [GD-Sync/GD-Sync#23]
Hi all,

Just wondering if it's possible to implement a function to allow for Automatic Bans?

I have implemented a Profanity filter that allows a certain amount of warnings before the player gets banned for excessive use of profanities (my game is aimed at Ages 8 and up).

At the moment, the only functionality is to report a user, but the reporter cannot have more than 1 open report against a user at a time. Ideally, I would like functionality that can bypass the report system and automatically ban a user based on logic within the game.

Thanks in advance

**Comment by ThomasUijlen** [comment]
Hi there,

A new function, `GDSync.ban_account(ban_duration : float)`, has been implemented. This allows you to ban the currently logged-in account right from within the engine.

You can download the newest version right here from GitHub or from the Asset Library in a few days once the changes have been approved.
