### ISSUE TITLE
Method 'create_lobby' unclear documentation / usage between online and local servers.

### ISSUE THREAD

**Issue by dragmine149** [GD-Sync/GD-Sync#24]
## The problem
The documentation for the method `create_lobby()` declares that
> If no player limit is provided the limit will automatically be set to the maximum your plan allows.

However this is not the case for the local multiplayer system GDSync supports (Potentially due to no request being sent to the server to get the plan limit). As setting no player limit will set the lobby size to 0. Hence not allowing anyone to join the lobby.

Although this is an easy fix, it would be nice not to have two separate arguments for the same function when most of the other functions already work without changing something.

**Comment by ThomasUijlen** [comment]
Hi there!

Thank you for notifying us of this issue. A fix for this issue has now been pushed. When creating a local lobby with a player_limit of 0, it now removes the player limit entirely.
