### ISSUE TITLE
State Machine and Composition nodes.

### ISSUE THREAD

**Issue by Galllaa** [GD-Sync/GD-Sync#3]
Hi, 
I was trying to reach out over the website and support ticket but after a couple of days and no reply I'm trying it here.
Its probably my fault but I'm not sure how to setup it with a state machine example : I'm calling transition to Die-state and it triggers only on the player that should die but when I try to reset the position of the player it resets both players positions. I tried to debug it and only the player that should transition to Die is transitioning but when it comes to the part where the player should reset the position it triggers on both players and I'm not sure why. Any help is appreciated. Thank you in advance.

**Comment by ThomasUijlen** [comment]
Closing this as it has been resolved via email.
