### ISSUE TITLE
Issue with creating and joining a lobby

### ISSUE THREAD

**Issue by mrjshzk** [GD-Sync/GD-Sync#5]
Hello and first of all I want to congratulate the work that has been done, this is truly awesome! I am attempting to learn this by the demo project and currently I have a made a simple name creator and choosing to create or join a lobby.

My current issue is that when a lobby is created, I switch the client to the lobby scene which should also add a label with its name, but the one that creates the lobby doesn't receive the "client_joined" signal and only works for people joining.

I attach my project in a zip file, using latest stable Godot version.

Run 2 or more instances to check this error for yourself
[online - Copy.zip](https://github.com/GD-Sync/GD-Sync/files/15215122/online.-.Copy.zip)

**Comment by ThomasUijlen** [comment]
Hi there!

I will look into the issue. Please be aware that you have included your API key in the project. I recommend generating a new key and deleting the one included in the attached project.

**Comment by ThomasUijlen** [comment]
I have looked into the project you have sent me. Godot doesn't seem to instantly transition to the lobby when using `get_tree().change_scene_to_file()`. This causes the client_joined signal to be emitted while still in the **lobby_manager** scene.

This issue can easily be resolved by adjusting the lobby script to also show all already existing clients:
```
extends Control

@onready var username_container: VBoxContainer = $CenterContainer/VBoxContainer

# Called when the node enters the scene tree for the first time.
func _ready() -> void:
	GDSync.client_joined.connect(client_joined)
	
	for client_id in GDSync.get_all_clients():
		client_joined(client_id)


func client_joined(client_id : int) -> void:
	print("Client joined - " + str(client_id))
	var label := Label.new()
	label.text = GDSync.get_player_data(client_id, "Username")
	$CenterContainer/VBoxContainer.add_child(label)

```


Please let me know if this resolves your issue.

**Comment by mrjshzk** [comment]
Just fixed and came back here and you found another solution! 

This was the faulty code and it works now that I've changed "_ready" to "_init".
![image](https://github.com/GD-Sync/GD-Sync/assets/115943663/253f0481-b19f-4e17-bb9f-80595bd024c4)

I will also add that snippet to the ready (now _init) function. Thank you so much!
