### ISSUE TITLE
Add C# support

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#6]
I'm currently trying to integrate GD Sync into a test project, but it is tedious to use Godots default cross language scripting capabilities to access the GD classes.

I propose that in futures version C# will be supported out of the box.

**Comment by ThomasUijlen** [comment]
Hi there!

Thank you for the suggestion.  Godot's cross language support can indeed be quite tedious to use, especially in cases where it needs to happen often. We will look into creating an extended version that exposes the full GD-Sync API in C#.

It might take some time, as we are currently heavily focusing on finishing up persistent data/cloud storage support.

**Comment by ThomasUijlen** [comment]
Hi there!

C# support has just been pushed to the main branch. It is not yet available on the asset store. If you go to the configuration menu you can now enable C# support. This will automatically download and enable a C# version of the GD-Sync API.

If you have time to try it out, please let me know if you encounter any issues. I will mark this as complete when we release new patch notes.

**Comment by Deltt** [comment]
Excellent! Saw this way too late, I'll definitely try it out!
