### ISSUE TITLE
Add tightly synchronized clock and/or timer nodes / functionality

### ISSUE THREAD

**Issue by Deltt** [GD-Sync/GD-Sync#7]
Hello there,

It would be excellent if we could have a node, functionality or anything similar that would make it easy to continually keep a real-time clock synchronized across clients. I searched among the documentation for anything like this but couldn't find any. This would make the management of time-based events or times frames much easier and more approachable to less experienced users like me.

Potential use cases would be anything from party mini-games to any all sorts of competitive ranking games.

**Comment by ThomasUijlen** [comment]
Hi there!

Thank you for the feature request, it is indeed a solid one to add to the plugin. We have added it to our roadmap.

**Comment by ThomasUijlen** [comment]
Could you please clarify how you envision this feature working? Providing pseudocode or specific examples would be very helpful.

**Comment by Deltt** [comment]
I unfortunately can't provide any pseudocode as I don't have a deep enough understanding of netcode to think of a possible implementation,

but at the core, the functionality I'm describing would provide a way to almost perfectly synchronize an event in real-time, for example the start of a race or time related competitive scenarios.

I guess these use cases are rather niche tho

**Comment by ThomasUijlen** [comment]
Hi there!

This feature has now been implemented. It is a new feature called "Time Synchronized Events". It can be downloaded right now here from this repo, it will be available on the asset library in a few days.

For usage instructions, please check out the new [documentation](https://www.gd-sync.com/documentation#synchronizedevents).
