### ISSUE TITLE
Usernames are "" when calling GDSync.get_all_player_data(). But when on the dashboard, it's what was provided

### ISSUE THREAD

**Issue by KccbzZ** [GD-Sync/GD-Sync#9]
Hey there! Thank you so much for making this plugin first of all, it's so nice to use. :)

I was experimenting with the new account system, and I realize that the username is not retreivable using `GDSync.get_all_player_data(GDSync.get_client_id())` nor `GDSync.get_player_data(GDSync.get_client_id())`.

Perhaps am I misusing the new system?

Here's the important bits to my code as they are, just made some variables clearer (like email, password etc), registering and logging in:

### Authentication Code:
```gdscript

func _ready() -> void:
	GDSync.start_multiplayer()

# None of these are called when GDSync.is_active() is false:

# Login
func _on_login_pressed():
	var response := await GDSync.login(email, password)
	var response_code : int = response["Code"]
	if response_code == ENUMS.LOGIN_RESPONSE_CODE.SUCCESS:
		authentication_successful()

# Register
func _on_register_pressed():
	var response_code := await GDSync.create_account(email, username, password)
	if response_code == ENUMS.ACCOUNT_CREATION_RESPONSE_CODE.SUCCESS:
		show_verification_form() # Gets the user to input the code

# Verify
func _on_verify_pressed():
	var response := await GDSync.verify_account(email, verifiaction_code)
	if response == ENUMS.ACCOUNT_VERIFICATION_RESPONSE_CODE.SUCCESS:
	await GDSync.login(email, password)
	authentication_successful()

# User logged in
func authentication_successful():
	print(GDSync.get_all_player_data(GDSync.get_client_id()))
```

Using this, the output from `authentication_successful()` is the following:
```
{ "ID": 1447, "Username": "" }
```

**Comment by ThomasUijlen** [comment]
Hi there!

Currently, account usernames and the usernames used in lobbies are two separate things. The main reason for this is that persistent data storage is an entirely separate system that currently has no ties to the existing servers.

For now, you must set the usernames manually with GDSync.set_username().

We will make sure to fix this in our next update so that lobby usernames are automatically set when logged in.

**Comment by KccbzZ** [comment]
Ahh thank you for the clarification, I understand.

For anyone else that experiences this issue I just had the thought that upon registering, the username could be saved using the persistent data storage, and fetched upon logging in. I'll try that out today.

**Comment by ThomasUijlen** [comment]
Hi again,

I've pushed the changes I was talking about earlier. This new version is not yet available on the Godot Asset Library, but you can download it from this repo.

The plugin should now automatically assign the correct usernames when you log in. Please let me know if you encounter any issues with these new changes.

**Comment by KccbzZ** [comment]
Hi Thomas,

Sounds good, I'll give it a try later today and let you know if I find any issues.

**Comment by ThomasUijlen** [comment]
Thanks for testing it out! Closing this issue.
